#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "acropolis"
name = "Acropolis"
description.en = "Dynamic fork of diaspora*'s federated social network"
description.fr = "Fourche dynamique du réseau social fédéré de diaspora*"

version = "2022.01.29~ynh2"

maintainers = ["weex"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://magicstone.dev"
code = "https://github.com/magicstone-dev/acropolis"

[integration]
yunohost = ">=11.2"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...


[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    help.en = "For federation to work, this needs to be true. False is ok if you want to run a private instance."
    type = "group"
    default = "visitors"

    [install.email]
    ask.en = "Enter email address for administative notifications."
    type = "string"

    [install.password]
    type = "password"

[resources]
    [resources.sources.main]
    url = "https://github.com/magicstone-dev/acropolis/archive/f586f64b4cee0b2a50f45b5cf6de4e1fd749def8.tar.gz"
    sha256 = "716d9c5e1e8e7d2694dbe6d2c1b5e48e5a5537a29ec8a8d0a722e6750fffae56"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    web.default = 3000

    [resources.apt]
    packages = [
        "g++",
        # "libjemalloc1|libjemalloc2",
        "libjemalloc-dev",
        "zlib1g-dev",
        "libreadline-dev",
        "libpq-dev",
        "libssl-dev",
        "libyaml-dev",
        "libcurl4-dev",
        "libapr1-dev",
        "libxslt1-dev",
        "libidn11-dev",
        "libxml2-dev",
        "vim",
        "imagemagick",
        "postgresql",
        "postgresql-server-dev-all",
        "postgresql-contrib",
        "optipng",
        "jhead",
        "jpegoptim",
        "gifsicle",
        "brotli",
        "cmake",
        "pkg-config"
    ]

    [resources.database]
    type = "postgresql"
