#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.email = "admin@domain.tld"

    exclude = [
        "install.subdir"
    ]

    [default.test_upgrade_from.dc712d6bf6dd2f67b9863b03b8a6a3705713a81c]
    name = "previous version"

    args.admin = "package_checker"
    args.email = "admin@domain.tld"
    args.password = "1Strong-Password"
    args.domain = "domain.tld"
