#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source ynh_add_swap
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status "$app-web" >/dev/null; then
    yunohost service remove "$app-web"
fi
ynh_remove_systemd_config --service="$app-web"

if ynh_exec_warn_less yunohost service status "$app-sidekiq" >/dev/null; then
    yunohost service remove "$app-sidekiq"
fi
ynh_remove_systemd_config --service="$app-sidekiq"

ynh_remove_nginx_config

#=================================================
# REMOVE VARIOUS FILES
#=================================================

ynh_secure_remove --file="/etc/$app"


ynh_script_progression --message="Removing Swap..." --weight=1
ynh_del_swap

ynh_script_progression --message="Uninstalling Ruby..." --weight=1
ynh_remove_ruby

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
